spring.application.name=demo
# Database
spring.datasource.url=jdbc:mysql://localhost:3306/event_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# --- Mailtrap Email Settings ---
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525

# REPLACE THE TWO LINES BELOW WITH YOUR COPIED CREDENTIALS
spring.mail.username=aa29b138044d4e
spring.mail.password=4891a10241ee4c

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp